apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    name: grafana-svc
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
  selector:
    env: grafana-pod
  type: NodePort