apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    name: prometheus-svc
spec:
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    env: prom-pod
  type: NodePort